/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "TerraModulus"
include("internal", "kernel")
rootProject.children.forEach {
    it.projectDir = File(settingsDir, "src/${it.name}")
    include("${it.name}:common", "${it.name}:client", "${it.name}:server")
}

include("ferricia") // this is Rust

includeBuild("vector-math") {
    dependencySubstitution {
        substitute(module("com.cout970:kotlin-vector-math")).using(project(":"))
    }
}
